Determining if the pthread_create exist failed with the following output:
Change Dir: /home/gastondg/Documentos/OpenCV_test/facerecognition/dlib-19.17/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_015c1/fast"
/usr/bin/make -f CMakeFiles/cmTC_015c1.dir/build.make CMakeFiles/cmTC_015c1.dir/build
make[1]: se entra en el directorio '/home/gastondg/Documentos/OpenCV_test/facerecognition/dlib-19.17/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_015c1.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fPIE   -o CMakeFiles/cmTC_015c1.dir/CheckSymbolExists.c.o   -c /home/gastondg/Documentos/OpenCV_test/facerecognition/dlib-19.17/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_015c1
/home/gastondg/Documentos/OpenCV_test/env/lib/python3.7/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_015c1.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_015c1.dir/CheckSymbolExists.c.o  -o cmTC_015c1 
/usr/bin/ld: CMakeFiles/cmTC_015c1.dir/CheckSymbolExists.c.o: en la función `main':
CheckSymbolExists.c:(.text+0x1b): referencia a `pthread_create' sin definir
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_015c1.dir/build.make:87: cmTC_015c1] Error 1
make[1]: se sale del directorio '/home/gastondg/Documentos/OpenCV_test/facerecognition/dlib-19.17/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_015c1/fast] Error 2

File /home/gastondg/Documentos/OpenCV_test/facerecognition/dlib-19.17/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/gastondg/Documentos/OpenCV_test/facerecognition/dlib-19.17/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_61388/fast"
/usr/bin/make -f CMakeFiles/cmTC_61388.dir/build.make CMakeFiles/cmTC_61388.dir/build
make[1]: se entra en el directorio '/home/gastondg/Documentos/OpenCV_test/facerecognition/dlib-19.17/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_61388.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create -fPIE   -o CMakeFiles/cmTC_61388.dir/CheckFunctionExists.c.o   -c /home/gastondg/Documentos/OpenCV_test/env/lib/python3.7/site-packages/cmake/data/share/cmake-3.13/Modules/CheckFunctionExists.c
Linking C executable cmTC_61388
/home/gastondg/Documentos/OpenCV_test/env/lib/python3.7/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_61388.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_61388.dir/CheckFunctionExists.c.o  -o cmTC_61388 -lpthreads 
/usr/bin/ld: no se puede encontrar -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_61388.dir/build.make:87: cmTC_61388] Error 1
make[1]: se sale del directorio '/home/gastondg/Documentos/OpenCV_test/facerecognition/dlib-19.17/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_61388/fast] Error 2


Determining if the function sgemm_ exists failed with the following output:
Change Dir: /home/gastondg/Documentos/OpenCV_test/facerecognition/dlib-19.17/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_51f52/fast"
/usr/bin/make -f CMakeFiles/cmTC_51f52.dir/build.make CMakeFiles/cmTC_51f52.dir/build
make[1]: se entra en el directorio '/home/gastondg/Documentos/OpenCV_test/facerecognition/dlib-19.17/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_51f52.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=sgemm_ -fPIE   -o CMakeFiles/cmTC_51f52.dir/CheckFunctionExists.c.o   -c /home/gastondg/Documentos/OpenCV_test/env/lib/python3.7/site-packages/cmake/data/share/cmake-3.13/Modules/CheckFunctionExists.c
Linking C executable cmTC_51f52
/home/gastondg/Documentos/OpenCV_test/env/lib/python3.7/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_51f52.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=sgemm_    -rdynamic CMakeFiles/cmTC_51f52.dir/CheckFunctionExists.c.o  -o cmTC_51f52 
/usr/bin/ld: CMakeFiles/cmTC_51f52.dir/CheckFunctionExists.c.o: en la función `main':
CheckFunctionExists.c:(.text+0x10): referencia a `sgemm_' sin definir
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_51f52.dir/build.make:87: cmTC_51f52] Error 1
make[1]: se sale del directorio '/home/gastondg/Documentos/OpenCV_test/facerecognition/dlib-19.17/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_51f52/fast] Error 2


